baseURL = "https://shrenikm.com"
languageCode = "en-us"
title = ""

# Theme to use.
theme = "beautiful_hugo"

# Use chrome for syntax highlighting.
pygmentsUseClasses = true
pygmentsCodeFences = true

# Google analytics.
googleAnalytics = "G-4KBNN5G9DE"

# Disqus support.
disqusShortname = "https-shrenikm-com"

[markup.goldmark.renderer]
  unsafe= true


[Params]
  mainSections = ["posts"]
  dateFormat = "January 2, 2006"
  rss = true
  comments = true
  socialShare = true
  showRelatedPosts = true

  # Hide the author icon and name in each post card on the list view.
  hideAuthor = true

  # Client side syntax highlighting.
  useHLJS = true

  # Setting to true will hide disqus comments behind a button.
  delayDisqus = false

  # Github commit SHA footer.
  # commit = "https://github.com/shrenikm/blah"

  # Enable inline shortcodes.
  enableInlineShortcodes = true

  # Use MathJax (From: https://github.com/StevenDoesStuffs/beautifulhugo)
  disableMath = false
  useMathJax = true


[Author]
  name = "Shrenik M"
  email = "shrenik95@gmail.com"
  github = "shrenikm"
  linkedin = "shrenik95"


[[menu.main]]
  name = "Posts"
  url = ""
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "pages/projects/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "pages/about/"
  weight = 3


[[menu.main]]
  name = "Tags"
  url = "tags"
  weight = 4
